### ISSUE TITLE
Styles are missing while rendering FERC XBRL HTML using arellecmdline.exe

### ISSUE THREAD

**Issue by nagsystrends** [xbrlus/ferc-renderer#4]
Styles are missing while rendering FERC XBRL HTML using arellecmdline.exe

I have tried FERC XBRL HTML rendering using arellecmdline.exe as follows:

C:\Program Files\Arelle>arellecmdline --plugin FERC/render --ferc-render-render --ferc-render-template-set "https://github.com/xbrlus/ferc-renderer/blob/master/RenderingTemplates/Form_1.zip?raw=tru" -f "E:\Test\TestF1.xbrl" --ferc-render-inline "E:\Test\XBRL_8_739_20210211140935_xbrl.html" --noCertificateCheck --ferc-render-debug

Please find the attached Zip file.

[XBRL_8_739_20210211140935_xbrl.zip](https://github.com/xbrlus/ferc-renderer/files/6271088/XBRL_8_739_20210211140935_xbrl.zip)

**Comment by campbellpryde** [comment]
The css should be put in the same folder as E:\Test\XBRL_8_739_20210211140935_xbrl.html. The css file is here:
https://github.com/xbrlus/ferc-renderer/blob/master/plugin/FERC/form-template.css

Alternatively add the argument --ferc-render-css-file={Location of CSS file} and --ferc-render-inline-css . This will put the CSS in the file.

**Comment by campbellpryde** [comment]
To see the command parameters use the following:
C:\Program Files\Arelle>arellecmdline --plugin "xule | FERC/render" --help

**Comment by nagsystrends** [comment]
> To see the command parameters use the following:
> C:\Program Files\Arelle>arellecmdline --plugin "xule | FERC/render" --help

Issue fixed. Thank you

**Comment by nagsystrends** [comment]
> To see the command parameters use the following:
> C:\Program Files\Arelle>arellecmdline --plugin "xule | FERC/render" --help

Issue fixed. Thank you.
