### ISSUE TITLE
FERC XBRL Taxonomy for Form1 not loading taxonomy definition for "114 - Schedule - Statement of Income"

### ISSUE THREAD

**Issue by nagsystrends** [xbrlus/ferc-renderer#7]
I am unable to load Form 1 FERC XBRL taxonomy definitions for  schedule  **114 - Schedule - Statement of Income**.

As per my understanding, the  Form 1 **Schedule - General Information**  schema definition is the root cause for this issue. 

**Please find the Taxonomy files for Generation Information :**

![image](https://user-images.githubusercontent.com/82093352/116873824-f181ec80-ac35-11eb-889e-f9f57ffea399.png)

as shown in the screenshot, Generation information xsd is loading  incomplete  taxonomy definition  for  114 - Schedule - Statement of Income. 

**Please find the Taxonomy files for 114 - Schedule - Statement of Income :**

![image](https://user-images.githubusercontent.com/82093352/116873906-170ef600-ac36-11eb-838b-3ef286c2d66e.png)

**Comment by nagsystrends** [comment]
> I am unable to load Form 1 FERC XBRL taxonomy definitions for schedule **114 - Schedule - Statement of Income**.
> 
> As per my understanding, the Form 1 **Schedule - General Information** schema definition is the root cause for this issue.
> 
> **Please find the Taxonomy files for Generation Information :**
> 
> ![image](https://user-images.githubusercontent.com/82093352/116873824-f181ec80-ac35-11eb-889e-f9f57ffea399.png)
> 
> as shown in the screenshot, Generation information xsd is loading incomplete taxonomy definition for 114 - Schedule - Statement of Income.
> 
> **Please find the Taxonomy files for 114 - Schedule - Statement of Income :**
> 
> ![image](https://user-images.githubusercontent.com/82093352/116873906-170ef600-ac36-11eb-838b-3ef286c2d66e.png)

**Comment by campbellpryde** [comment]
I am able to load these files and get the complete income statement and
general information, what information is missing specifically? Even though
these have the same name the files a different in different locations.
Clearly this needs to be resolved but we cannot see any issues in the
underlying semantics.

Campbell Pryde

President and CEO

XBRL US Inc.


***@***.*** ***@***.***>*

*https://xbrl.us <https://xbrl.us>*

+ 1 (917) 582-6159 (Mobile)


[image: XBRL US]

The non-profit community <https://xbrl.us/xusmembers> improving U.S.
reporting through a free, open standard
<https://xbrl.us/home/learn/free-open-standards/>.
